version: "3.8"

services:
  opencv_server:
    image: localhost.local/mjpegazer:${IMAGE_TAG:-latest}
    extends:
      file: docker/build.yml
      service: opencv_server
    environment:
      - VIDEO_URL=http://webcam.rhein-taunus-krematorium.de/mjpg/video.mjpg
    ports:
      - 5000:5000
    restart: always
